// Flat C exports observed in AppXDeploymentClient.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef APPXDEPLOYMENTCLIENT_C_H
#define APPXDEPLOYMENTCLIENT_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: GetMetadataRootForPackage (ABI unverified)
// Export: GetNotificationPayloadForUser (ABI unverified)
// Export: GetApplicability5 (ABI unverified)
// Export: RegisterNotificationForUser (ABI unverified)
// Export: UnregisterNotificationForUser (ABI unverified)
// Export: GetPackageRegistrationStatusForUser (ABI unverified)
// Export: GetPackageRegistrationStatusForUserAndDefaultAccount (ABI unverified)
// Export: EnsurePackageFamilyIsRegisteredBeforeActivation (ABI unverified)
// Export: DllCanUnloadNow (ABI unverified)
// Export: DllGetClassObject (ABI unverified)
// Export: DeleteApplicabilityInfoArray (ABI unverified)
// Export: AppxValidatePackagesWithOptions (ABI unverified)
// Export: IsSharedAppsEnabled (ABI unverified)
// Export: ClientDeleteAllPackagesFromMainPackageArray (ABI unverified)
// Export: CheckComCallerHasCapabilities (ABI unverified)
// Export: NotifyPackageStatusChanged (ABI unverified)
// Export: ClientGetAllPackagesToBeInstalledForUser (ABI unverified)
// Export: UnregisterNotification (ABI unverified)
// Export: RegisterNotification (ABI unverified)
// Export: DllGetActivationFactory (ABI unverified)
// Export: GetApplicability (ABI unverified)
// Export: AppxAddPackageToAllUserStoreForPbr (ABI unverified)
// Export: AppxPackageRepositoryRecoverStagedPackages (ABI unverified)
// Export: AppxPackageRepositoryRecoverUserInstalls (ABI unverified)
// Export: AppxProfileNotificationHandler::OnLoad (ABI unverified)
// Export: AppxProfileNotificationHandler::OnMigrate (ABI unverified)
// Export: AppxProfileNotificationHandler::OnUnload (ABI unverified)
// Export: AppxProfileNotificationHandler::OnUpgrade (ABI unverified)
// Export: AppxRecoverUserInstallsForUpgrade (ABI unverified)
// Export: FixJunctionsForAppsIfNecessary (ABI unverified)
// Export: GetApplicability2 (ABI unverified)
// Export: GetApplicability4 (ABI unverified)
// Export: PackageRepository::RepositorySession::GetPackageRow (ABI unverified)
// Export: PackageRepository::VisibilityTable::FilterOnUserSidPackageKey (ABI unverified)
// Export: #ordinal1 (ABI unverified)
// Export: GetPackageDiskUsage (ABI unverified)
// Export: MsixIsPackageFeatureSupported (ABI unverified)
// Export: MsixIsPackageRegisteredOrNewerAvailable (ABI unverified)
// Export: MsixIsPayloadFileStaged (ABI unverified)
// Export: AppInstallerUpdateAllTask (ABI unverified)
// Export: AppxCleanupOrphanPackages (ABI unverified)
// Export: AppxCleanupSystemAppsMigratedToFOD (ABI unverified)
// Export: AppxCleanupWCIReparsePoints (ABI unverified)
// Export: AppxCreateSharedLocalFolder (ABI unverified)
// Export: AppxCreateSharedLocalFolderForFamilyName (ABI unverified)
// Export: AppxDeletePackageFiles (ABI unverified)
// Export: AppxDestagePackage (ABI unverified)
// Export: AppxDoesSharedLocalFolderExistForFamilyName (ABI unverified)
// Export: AppxGetPackageInstalledLocation (ABI unverified)
// Export: AppxGetStagedPackageFullNameFromFamilyName (ABI unverified)
// Export: AppxIsStagedPackageStoreSigned (ABI unverified)
// Export: AppxPreRegisterAllInboxPackages (ABI unverified)
// Export: AppxPreRegisterPackage (ABI unverified)
// Export: AppxPreStageCleanupRunTask (ABI unverified)
// Export: AppxRegisterPackage (ABI unverified)
// Export: AppxRemoveAllPackagesForUserSid (ABI unverified)
// Export: AppxRemovePackageForAllUsers (ABI unverified)
// Export: AppxRemovePackageForUserSid (ABI unverified)
// Export: AppxRequestRemovePackageForUser (ABI unverified)
// Export: AppxResetPackage (ABI unverified)
// Export: AppxStagePackage (ABI unverified)
// Export: AppxStagePackage2 (ABI unverified)
// Export: AppxSvcPrepareForSysprepGeneralize (ABI unverified)
// Export: AppxValidatePackages (ABI unverified)
// Export: CheckAppInstallerUpdateAvailability (ABI unverified)
// Export: CheckForUpdatesAndWaitForInstallerIfNeeded (ABI unverified)
// Export: CleanupProfileForUser (ABI unverified)
// Export: ClientExistsAnyPackageToBeInstalledForUser (ABI unverified)
// Export: CreateCanonicalPriFile (ABI unverified)
// Export: DeleteAutoUpdateSettings (ABI unverified)
// Export: ExistPackagesPendingDeferredRemovalForUser (ABI unverified)
// Export: FreeApplicationSecret (ABI unverified)
// Export: #ordinal16 (ABI unverified)
// Export: GenerateBytecodeForPackages (ABI unverified)
// Export: GeneratePreInstalledPriFiles (ABI unverified)
// Export: GetApplicationSecret (ABI unverified)
// Export: GetBundleApplicablePackages (ABI unverified)
// Export: GetNotificationPayload (ABI unverified)
// Export: HasPackageFamilyBeenRegisteredForUser (ABI unverified)
// Export: IsPackageInstalled (ABI unverified)
// Export: IsPackageMetadataUnderSystemMetadata (ABI unverified)
// Export: MSIXForceReRegisterPackage (ABI unverified)
// Export: MsixAppxAllUserStoreIsInboxPackage (ABI unverified)
// Export: MsixEnsurePackageIsRegistered (ABI unverified)
// Export: MsixGetOutdatedPackagesForUser (ABI unverified)
// Export: MsixIsPackageRegistrationPending (ABI unverified)
// Export: MsixPackageVolumeIsRepairNeeded (ABI unverified)
// Export: MsixPackageVolumeRepair (ABI unverified)
// Export: MsixPreRegisterPackagesIfNeeded (ABI unverified)
// Export: MsixPreRegisterUupProducts (ABI unverified)
// Export: MsixRemovePackageByUriAsync (ABI unverified)
// Export: MsixRepairPackageAsync (ABI unverified)
// Export: MsixResetPackageAsync (ABI unverified)
// Export: PauseAutoUpdateSettings (ABI unverified)
// Export: PopulateProtocolAndFTA (ABI unverified)
// Export: RDSRecoverRequests (ABI unverified)
// Export: ReArmAppxPreStageCleanupTask (ABI unverified)
// Export: RemoveDeferredPackages (ABI unverified)
// Export: RepairPackageFileAcls (ABI unverified)
// Export: RequestContentGroups (ABI unverified)
// Export: RequestContentGroupsForFullTrust (ABI unverified)
// Export: ResetApplicationSecrets (ABI unverified)
// Export: ScheduleAppInstallerBackgroundUpdate (ABI unverified)
// Export: SetApplicationSecret (ABI unverified)
// Export: UpdateAgentCancelAllDownloads (ABI unverified)
// Export: UpdateAgentCancelDownload (ABI unverified)
// Export: UpdateAgentCreateDownload (ABI unverified)
// Export: UpdateAgentFreeDownloadRanges (ABI unverified)
// Export: UpdateAgentGetDownloadPackageReturnValue (ABI unverified)
// Export: UpdateAgentGetDownloadRanges (ABI unverified)
// Export: UpdateAgentGetDownloadingPackageCount (ABI unverified)
// Export: UpdateAppInstallerSettings (ABI unverified)
// Export: UpdateDataSourceAddRange (ABI unverified)
// Export: UpdateDataSourceCancelRun (ABI unverified)
// Export: UpdateDataSourceRegister (ABI unverified)
// Export: UpdateDataSourceRun (ABI unverified)
// Export: VerifyPackage (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // APPXDEPLOYMENTCLIENT_C_H
